version: '3.8'

services:
  order-db:
    image: postgres:15
    container_name: order_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: Order_db
    ports:
      - "5431:5432"
    networks:
      - microservices_net

  order-service:
    build: .
    container_name: order_service
    ports:
      - "8081:8080" 
    depends_on:
      - order-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/Order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=your_password_here
    networks:
      - microservices_net

networks:
  microservices_net:
    external: true