version: '3.8'

services:
  order-db:
    image: postgres:15
    container_name: order_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - microservices_net

  order-service:
    build: .
    container_name: order_service
    ports:
      - "${APP_PORT}:8080" 
    depends_on:
      - order-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - microservices_net

networks:
  microservices_net:
    external: true